### ISSUE TITLE
Cannot read property 'create' of undefined

### ISSUE THREAD

**Issue by mritzman-dg** [souvik-ghosh/react-native-create-thumbnail#11]
Getting the following error on Android and iOS when just importing the library like this:

`import { createThumbnail } from "react-native-create-thumbnail";`

Environment:
npm -version: `6.9.0`
node --version: `v10.16.1`
expo cli version: `3.13.1`

package.json dependencies:
`
"react": "16.8.3",
"react-dom": "16.8.3"
"expo": "^35.0.0",
"react-native": "https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz",
"react-native-create-thumbnail": "^1.0.5",
`

On Android Emulator:
![Screen Shot 2020-04-13 at 2 01 37 PM](https://user-images.githubusercontent.com/20933623/79158448-97e12280-7d93-11ea-8a1f-5212b21e1a79.png)

On iOS Emulator:
![Screen Shot 2020-04-13 at 2 01 50 PM](https://user-images.githubusercontent.com/20933623/79158450-99aae600-7d93-11ea-8207-c14133dd2b66.png)

**Comment by souvik-ghosh** [comment]
@mritzman-dg This library is a **native module**, so you can not use expo without ejecting. [https://docs.expo.io/versions/latest/bare/customizing/](https://docs.expo.io/versions/latest/bare/customizing/)
