### ISSUE TITLE
iOS 1.2.0 always throw "File doesn't exist or not supported"

### ISSUE THREAD

**Issue by soplwang** [souvik-ghosh/react-native-create-thumbnail#17]
**Describe the bug**
iOS 1.2.0 incorrect lowercase the source url that makes file not found issue on iOS (it's file system is case sensitive).

**To Reproduce**
1. Build iOS ImagePicker example app
2. Use image picker to export a video then pass it to `react-native-create-thumbnail`
3. It *ALWAYS* throws `FileNotSupportedException`

**Version**
1.2.0

**Comment by souvik-ghosh** [comment]
@soplwang Thanks for the contribution! v1.2.1 has been released.

**Comment by prakashw3expert** [comment]
i am still getting this error in   "react-native-create-thumbnail": "^1.2.1",
File doesn't exist or not supported

**Comment by ElChawich** [comment]
issue still persisting on iOS on v1.2.1

**Comment by tamsil25** [comment]
I'm running on the v1.4.1 and still have the same issue.
