### ISSUE TITLE
Add video time duration and video symbol on thumbnail 

### ISSUE THREAD

**Issue by ar0692** [souvik-ghosh/react-native-create-thumbnail#19]
can we add video time duration and video symbol on thumbnail, or any work around it

**Comment by souvik-ghosh** [comment]
@ar0692 Can you explain a bit more what you're trying to do? If you want to show anything on the thumbnail image, you can easily do that by having an overlay view or using something like [ImageBackground](https://reactnative.dev/docs/imagebackground)
