### ISSUE TITLE
how do i access thumbnail from local device file using react native video player

### ISSUE THREAD

**Issue by aleluiah** [souvik-ghosh/react-native-create-thumbnail#21]
i want to access thumb nail from local device file using react-native-video-player. below is my code 

<VideoPlayer resizeMode='stretch' thumbnail={{uri: 'file:///data/user/0/com/myfirstproject/cache/thumbnails/thumb-6d12fb87-4200-4a52-85ab-d9a0efa3720f.jpeg'}} repeat={false} playWhenInactive={false} video={{uri: urii}} style={{ maxWidth: '100%', height: 250, padding: 0, margin: 0 }} mediaPlaybackRequiresUserAction = {true} />

**Comment by souvik-ghosh** [comment]
@aleluiah in response of `createThumbnail` you will get the path to generated image(jpeg/png) file. Use this path to show the thumbnails like any other image.

**Comment by aleluiah** [comment]
thanks sir, iappreciate
