### ISSUE TITLE
Animations stutter while generating thumbnails

### ISSUE THREAD

**Issue by gfpacheco** [souvik-ghosh/react-native-create-thumbnail#24]
**Describe the bug**
When navigating to a new screen that has a few thumbnail components the navigation animation stutters because (I imagine) the thumbnails are being generated in the UI thread.

**To Reproduce**
1. add reactnavigation with two screens
2. on the first one add a button to navigate to the second
3. on the second add a few thumbnail components (that call `createThumbnail` on useEffect)

**Version**
`1.2.1`

**Expected Results**
The navigation animation runs smoothly and the thumbnails are generated asynchronously.

**Comment by leonardmns12** [comment]
@gfpacheco did you solve this problem?

**Comment by gfpacheco** [comment]
> @gfpacheco did you solve this problem?

Nop

**Comment by gecusdevus** [comment]
try to use this https://reactnative.dev/docs/interactionmanager

**Comment by souvik-ghosh** [comment]
@gfpacheco Can you try the solution suggested by @gecusdevus ?

**Comment by gfpacheco** [comment]
I'm sorry I can't. I don't even work on that project anymore

**Comment by souvik-ghosh** [comment]
Oh, I see. Closing this as of now.

**Comment by souvik-ghosh** [comment]
Reopened to test the scenario using https://reactnative.dev/docs/interactionmanager

**Comment by souvik-ghosh** [comment]
v1.5.0 is released with asynchronous thumbnail generation. Closing this as of now.
