### ISSUE TITLE
[Error: File doesn't exist or not supported]

### ISSUE THREAD

**Issue by Saad9624** [souvik-ghosh/react-native-create-thumbnail#26]
**Describe the bug**
The video uri is valid and playing in react-native-video but thumbnail is not being created  showing wrror

**Version**
^1.2.1

createThumbnail({
      url: path,
      timeStamp: 10000,
    })
    
      .then( (response) =>{
        console.log("Thumnnail path" ,  response );
        if(response.path){
          this.setState({
            imageUri:response.path
          })
        }
      } )

**Comment by ElChawich** [comment]
same issue here on iOS, m trying to create a thumbnail for this url "https://dev.libanroot.com:83/media/activities/laylatQadr_9UZbTO5.mp4" but it's giving an error saying "File doesn't exist or not supported".
I tried some other videos and it did work, but this one isn't. On android it's working perfectly.

**Comment by marwa-tarek** [comment]
Any updates on this issue? It happens to me too.

**Comment by ElChawich** [comment]
@marwa-tarek is it not working on both android and iOS for you? for me it was only on iOS and it was in issue from the server.

**Comment by lordival** [comment]
no working on android for me. IOS works fine

**Comment by souvik-ghosh** [comment]
Anyone still having this issue, can you please check with the latest version (1.3.0)?

**Comment by souvik-ghosh** [comment]
Closing this as of now

**Comment by Jim-Blair** [comment]
@mtahir08 Did you manage to solve it?
Still getting error on version 1.5.1

**Comment by tacianoscur** [comment]
I am getting the same error with an mp4 video, only happens to a specific video and on android, works fine with the same video on iOS.
`react native 0.72.11`
`react-native-create-thumbnail ^2.0.0`
