### ISSUE TITLE
Android- [Error: setDataSource failed: status = 0x80000000]

### ISSUE THREAD

**Issue by northoutaman** [souvik-ghosh/react-native-create-thumbnail#27]
In Android once I select the video from the gallery and I'm trying to create the thumbnail via video path in local storage getting the error.

Here the video path:
let response = {
"path": "/storage/emulated/0/DCIM/Camera/VID_20201001_112300280.mp4", 
"uri": "content://media/external/video/media/160894"
}

**Version**
react-native-create-thumbnail - ^1.2.1
Android version - 6.0

**Expected Results**
In iOS Working fine but in android getting error in catch block:
Error: [Error: setDataSource failed: status = 0x80000000]

**Code**
createThumbnail({
      url: response.path,
      timeStamp: 10000,
    })
      .then((response) => {
        console.log('response=', response);
        //this.uploadVideoThumbnailOnAWS(response.path);
      })
      .catch((err) => console.log('error=', err));

Also tried with the **Uri** key instead of the **path** key but getting the same issue.

**Comment by abhishektiwari-kiwi** [comment]
Any update on this?

**Comment by abhishektiwari-kiwi** [comment]
@northoutaman 
I was getting the same error, now resolved, turns out that the fileUri was wrong.
You need to be 100% sure that path for the file is not null, not empty, the file itself exists and valid.

**Comment by northoutaman** [comment]
> @northoutaman
> I was getting the same error, now resolved, turns out that the fileUri was wrong.
> You need to be 100% sure that path for the file is not null, not empty, the file itself exists and valid.

**Comment by northoutaman** [comment]
@abhishektiwari-kiwi I have validated and the file path is valid and it's not null and empty.

**Comment by abhishektiwari-kiwi** [comment]
@northoutaman 
Well then, please verify the below points.

1. uri should be a filePath, something like this
"file:///data/user/0/com.xxx/xxx/xxxx/xxxx.mp4"
2. you are querying thumbnail at 10th second so, make sure your video is long enough.
3. Make sure you are not decoding the filePath, because library itself do it internally.
4. Make sure you've given READ_EXTERNAL_STORAGE, WRITE_EXTERNAL_STORAGE permissions.

**Comment by 349989153** [comment]
@abhishektiwari-kiwi you're right, I just met the `filePath` issue

**Comment by pragadeeshk** [comment]
> @northoutaman
> Well then, please verify the below points.
> 
> 1. uri should be a filePath, something like this
>    "file:///data/user/0/com.xxx/xxx/xxxx/xxxx.mp4"
> 2. you are querying thumbnail at 10th second so, make sure your video is long enough.
> 3. Make sure you are not decoding the filePath, because library itself do it internally.
> 4. Make sure you've given READ_EXTERNAL_STORAGE, WRITE_EXTERNAL_STORAGE permissions.

@abhishektiwari-kiwi I am also facing the same issue. Does the library expect the path to begin with 'file://'.
In such case, is 'file:///storage/emulated/0/DCIM/Camera/VID_20201001_112300280.mp4' a valid path?
I am getting the same error on that case as well. Please advice.

**Comment by abhishektiwari-kiwi** [comment]
@pragadeeshk 
I'm just curious. Did you get this error while testing in emulator?

And Yes, the library internally verifies URLUtil.isFileUrl(filePath).
So, let me know if any other scenario you have along with this one?

**Comment by northoutaman** [comment]
@abhishektiwari-kiwi Thanks now it's working I missed the actual file path. sorry for the late reply.

**Comment by livefuture009** [comment]
I am getting this error for only below Android 9.0 devices and emulators.

file:///data/user/0/com.xxx/cache/rn_image_picker_lib_temp_47dc40e9-3526-46f6-bedd-b302aa846139.mp4
[Error: setDataSource failed: status = 0xFFFFFFEA]

This is the url that I have called. file is existing correctly. I had confirmed already.
On iOS & Android 10 devices, it's working as well. 

Could you give me option to solve it?

**Comment by Hamza-Khurshid** [comment]
On Android, I had fixed by making sure the url starts with file://somepath rather than /somepath only

**Comment by Its-Hacker** [comment]
ERROR [Error: setDataSource failed: status = 0xFFFFFFEA]

**Comment by andreatrio** [comment]
> ERROR [Error: setDataSource failed: status = 0xFFFFFFEA] how can we solve this ??

I had the same problem. The path I was using was 'data/user/0/....'. I was able to fix it by adding 'file://' at the beginning of the filePath. So in the end it was something like this:  'file://data/user/0/....'
