### ISSUE TITLE
react-native build error

### ISSUE THREAD

**Issue by KartikLakhani009** [souvik-ghosh/react-native-create-thumbnail#31]
**Describe the bug**
react-native run-android command execute it is stopped and give me an error like  Task :react-native-create-thumbnail:compileDebugJavaWithJavac

**To Reproduce**
Steps to reproduce the behaviour:
1../gradlew clean
2. node_module folder delete and npm install

**Version**
`react-native-create-thumbnail` :^1.2.1
 "react": "16.13.1",
 "react-native": "0.63.2",

more info 
/...path/app/node_modules/react-native-create-thumbnail/android/src/main/java/com/createthumbnail/CreateThumbnailModule.java:94: error: cannot find symbol
        Arrays.sort(files, LastModifiedFileComparator.LASTMODIFIED_COMPARATOR);
                           ^
  symbol:   variable LastModifiedFileComparator
  location: class CreateThumbnailModule
Note: /...path/app/node_modules/react-native-create-thumbnail/android/src/main/java/com/createthumbnail/CreateThumbnailModule.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors

**Comment by PrayaAmadigaPitasa** [comment]
confirmed, same with me

**Comment by Anzormumladze** [comment]
same!!!

**Comment by AnandhuSajeev** [comment]
Same Issue from 18th NOV 2020

**Comment by zohaib201** [comment]
In ~/react-native-create-thumbnail/android/build.gradle change
implementation 'commons-io:commons-io:+'
to
implementation 'commons-io:commons-io:2.8.0'

https://github.com/souvik-ghosh/react-native-create-thumbnail/issues/29#issuecomment-729062909

**Comment by souvik-ghosh** [comment]
Thanks, guys! v1.2.2 has been released with the fix.
