### ISSUE TITLE
Not working on android api 28 above

### ISSUE THREAD

**Issue by akug17** [souvik-ghosh/react-native-create-thumbnail#33]
While using api 29 or 30 the lib just doesn't work after giving it the correct file path it throws error:null,
whereas if I use it on api 28 it works. I couldn't find the issue I am also using react-native-media-meta which is having the same issue but the lib is not getting maintained anymore.

**Comment by souvik-ghosh** [comment]
Anyone still having this issue, can you please check with the latest version (1.3.0)?

**Comment by souvik-ghosh** [comment]
Closing this as of now
