### ISSUE TITLE
Does this implement cache?

### ISSUE THREAD

**Issue by petr166** [souvik-ghosh/react-native-create-thumbnail#4]
Hi, thanks for the useful library.

I'm wondering if `createThumbnail` generates a new jpeg on every call, regarding if `url` is the same. Because if so, I imagine it will quickly fill a lot of storage with unused images.

**Comment by souvik-ghosh** [comment]
@petr166 Glad you found it useful!

Well, currently it generates a new image on every call. I understand that cache implementation is a must and I would like to let you know that the work is in progress. Soon I will be releasing a new version with the implementation.

**Comment by souvik-ghosh** [comment]
@petr166 I have implemented a FIFO cache directory with 100mb max size. It will prevent the library from flooding storage.
