### ISSUE TITLE
Error: File doesn't exist or not supported

### ISSUE THREAD

**Issue by eakenbor** [souvik-ghosh/react-native-create-thumbnail#47]
I use react-native-image-crop-picker to take a picture using the camera and when I pass the path of the image to createThumbnail I get this error: "File doesn't exist or not supported". 

Here is my code:
````
ImagePicker.openCamera({
        width: windowFrame.width,
        height: windowFrame.height,
        cropping: true
      }).then(async response => {
createThumbnail({
          url: response.path,
          timeStamp: 10000,
        })
          .then(response => console.log({ response }))
          .catch(err => console.log({ err })) }
````

The response.path looks like this: "/private/var/mobile/Containers/Data/Application/RR62F5C8-26F5-4B9A-8A3F-3D65BE6207FF/tmp/react-native-image-crop-picker/A90DD27F-6E4E-4E70-B678-D595D84A13F9.jpg"

Please can someone tell me where I got this wrong? Thanks.

**Comment by DoanDat2511** [comment]
I have the same problem as you.
you have solution yet ?

**Comment by honghong01** [comment]
Same issue.
Problems occur with high-definition video.

**Comment by souvik-ghosh** [comment]
@eakenbor This library creates a thumbnail from video files only. You're passing a JPEG image.
