### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by abdullahIsa** [souvik-ghosh/react-native-create-thumbnail#57]
Hello, i am getting this error

Error: Requiring module "node_modules\react-native-create-thumbnail\index.js", which threw an exception: TypeError: Cannot read property 'create' of null, js engine: hermes

{"err": [TypeError: Cannot read property 'createThumbnail' of undefined]}

**Comment by abdullahIsa** [comment]
Hello, sorry works now, just realized this is for video only and also must re-start the project to take effect, thanks.

**Comment by fukemy** [comment]
i got same problem with path 
```
file:///Users/thehe/Library/Developer/CoreSimulator/Devices/4E521778-529B-4CB3-BAE7-78DF753890D0/data/Containers/Data/Application/3EF8F5E0-FB03-4A94-8624-FEE88494FF04/tmp/react-native-image-crop-picker/5D6BC16C-A4C4-49F3-AD5C-09B1E0494570.mp4
```
