### ISSUE TITLE
setDataSource failed error

### ISSUE THREAD

**Issue by sania232** [souvik-ghosh/react-native-create-thumbnail#62]
When Im trying this with a youtube video URL it is giving me the below error:
`setDataSource failed: status = 0x80000000`
I followed the example code and am using React Native CLI

**Comment by Subiyel** [comment]
Same here getting following error: 
Error: setDataSource failed: status = 0xFFFFFFEA

`try {
        const response = await createThumbnail({
          url: absolutePath,
          timeStamp: 1,
        });
        console.log("Thumbnail: ", response.path);
      } catch (err) {
        console.error(err);
      } `

**Comment by souvik-ghosh** [comment]
@sania232 @Subiyel I need a few inputs. Can you please check if the video is playable(using react-native-video) on the device? (using the same path)

**Comment by Subiyel** [comment]
Yes, the video is playable using the same path via react-native-video. i am picking the video using react-native-image-picker.
For temporary workaround i am now uploading the video to my server and using that url to create thumbnail and it works fine. Issue is occurring only using local file path.

**Comment by AdamTyler** [comment]
I'm also running into this issue on Android only. For all thumbnails the return I see is: `{"err": [Error: setDataSource failed: status = 0xFFFFFFEA]}`.

```
        buildToolsVersion = "30.0.2"
        minSdkVersion = 24
        compileSdkVersion = 31
        targetSdkVersion = 30
        ndkVersion = "21.4.7075529"
        kotlinVersion = '1.5.0'
        supportLibVersion = "29"
        playServicesVersion = "17.0.0"
```

```
"react-native-create-thumbnail": "^1.5.1",
"react-native": "^0.67.4"
```

**Comment by ranjitAcelucid** [comment]
Hii @tudormarze ,
Could you provide me the example of this? How can you implemented it?


Thanks

**Comment by vrsmk1995** [comment]
> @sania232 @Subiyel I need a few inputs. Can you please check if the video is playable(using react-native-video) on the device? (using the same path)

iam using youtube url links for creating thumbnails iam getting same error 
[app.json](https://github.com/souvik-ghosh/react-native-create-thumbnail/files/14079585/app.json)
[app.json](https://github.com/souvik-ghosh/react-native-create-thumbnail/files/14079586/app.json)

import React, {useState} from 'react';
import {
  Image,
  Text,
  View,
  StyleSheet,
  TextInput,
  Button,
  ActivityIndicator,
} from 'react-native';
import {createThumbnail} from 'react-native-create-thumbnail';

const placeholderImage = require('./Images/image.png');

const App = () => {
  const [path, setPath] = useState('');
  const [thumbnail, setThumbnail] = useState('');
  const [timeStamp, setTimeStamp] = useState('1000');
  const [isLoading, setIsLoading] = useState(false);

  return (
    <View style={styles.container}>
      <Text style={styles.welcome}>☆CreateThumbnail example☆</Text>
      <TextInput
        value={path}
        onChangeText={setPath}
        style={styles.pathInput}
        placeholder="Paste video url"
        placeholderTextColor="lightgrey"
      />
      <TextInput
        keyboardType="numeric"
        value={timeStamp}
        onChangeText={setTimeStamp}
        style={styles.timeInput}
        placeholder="Timestamp"
      />
      <Button
        title="Generate Thumbnail"
        disabled={isLoading}
        onPress={generateThumbnail}
      />
      <Text style={styles.welcome}>☆THUMBNAIL☆</Text>
      <View style={styles.image}>
        {isLoading ? (
          <ActivityIndicator size="large" />
        ) : (
          <Image
            style={styles.image}
            source={thumbnail ? {uri: thumbnail} : placeholderImage}
          />
        )}
      </View>
    </View>
  );

  async function generateThumbnail() {
    if (!path) {
      return;
    }

    setIsLoading(true);

    try {
      const response = await createThumbnail({
        url: path,
        timeStamp: parseInt(timeStamp, 10),
      });
      setThumbnail(response.path);
    } catch (err) {
      console.error(err, 'error');
    } finally {
      setIsLoading(false);
    }
  }
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 20,
    color: 'black',
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 20,
  },
  image: {
    height: 150,
    width: 250,
    backgroundColor: 'lightgrey',
    justifyContent: 'center',
  },
  pathInput: {
    backgroundColor: '#eaeaea',
    width: '80%',
    paddingHorizontal: 10,
    color: 'black',
    borderColor: 'lightgrey',
    borderWidth: 1,
  },
  timeInput: {
    backgroundColor: '#eaeaea',
    width: '40%',
    paddingHorizontal: 10,
    margin: 20,
    color: 'black',
    borderColor: 'lightgrey',
    borderWidth: 1,
  },
});

export default App;
this is my code can u please help

**Comment by souvik-ghosh** [comment]
@vrsmk1995 Youtube links won't work. This library only supports direct links to videos.

**Comment by vrsmk1995** [comment]
is there any solution for HLS player videos support with this plugin

**Comment by ahsanreal4** [comment]
@vrsmk1995 Any breakthrough on HLS player support ?

**Comment by yStudMed** [comment]
should I make sure it is file:// uri in the native java code or what ? I already provide file:// uri but sometimes get setDataSource failed: status = 0x80000000 !

**Comment by Splicer97** [comment]
Similar issue
