### ISSUE TITLE
Could not resolve all files for configuration build error

### ISSUE THREAD

**Issue by remorr25** [souvik-ghosh/react-native-create-thumbnail#68]
**Describe the bug**
While compile the app getting error **Could not resolve all files for configuration ':react-native-create-thumbnail:implementation'.**

**To Reproduce**
1. Run the app with latest react native configuration

**Version**
"react": "18.0.0",
"react-native": "0.69.1",
"react-native-create-thumbnail": ^1.5.1

**Expected Results**
App should be compile and run on device
![Screen Shot 2022-07-11 at 12 52 45 PM](https://user-images.githubusercontent.com/6324053/178210207-98de7f05-78e7-439f-bcde-7fd053c1a424.png)

**Comment by remorr25** [comment]
@LucasClaude sorry not yet.

**Comment by rewdt** [comment]
I'm stuck on the same issue

**Comment by remorr25** [comment]
@maugonsal Thanks

**Comment by fukemy** [comment]
not working to me

**Comment by shankar24r** [comment]
Unable to compile the project.

Could not resolve all files for configuration ':react-native-create-thumbnail:implementation'.

**Comment by fukemy** [comment]
yes I got exactly same issues, dont know why

**Comment by Veerasathiya** [comment]
remove jcenter() from android/build.gradle

`    repositories {
        google()
        // jcenter()
        mavenCentral()
    }

allprojects {
    repositories {
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }
        mavenCentral {
            // We don't want to fetch react-native from Maven Central as there are
            // older versions over there.
            content {
                excludeGroup "com.facebook.react"
            }
        }
        mavenLocal()
        maven { url 'https://maven.google.com' }
        google()
        // jcenter()
        maven { url 'https://www.jitpack.io' }
    }
}
`

**Comment by YuriBSSE** [comment]
> remove jcenter() from android/build.gradle
> 
> ```
> repositories {
>        ...
>       // jcenter()
> }
> 
> allprojects {
>     repositories {
>         ...
>         // jcenter()
>     }
> }
> ```

Perfectly Fine, Thank You @Veerasathiya 👍

**Comment by ZakirBangash** [comment]
same here non of the above solution worked for me

**Comment by mcrzx** [comment]
same issue

**Comment by AhmedAbuelenin** [comment]
> 

This worked for me, thank you. For whom this didn't work him, you should replace first "afterEvaluate", "def myAttribute", "dependencies.attributesSchema" and "configurations"  with 

subprojects {
    afterEvaluate { subproject ->
        if(subproject['name'] == 'react-native-create-thumbnail'){
            def myAttribute = Attribute.of("com.android.build.api.attributes.BuildTypeAttr", String)
            dependencies.attributesSchema {
                attribute(myAttribute)
            }
            configurations {
                implementation {
                    attributes {
                        attribute(myAttribute, "release")
                    }
                }
            }
        }
    }
}
