### ISSUE TITLE
Unable to compile for Android 13 (Android SDK v.33)

### ISSUE THREAD

**Issue by kakato10** [souvik-ghosh/react-native-create-thumbnail#69]
**Describe the bug**
Unable to compile `react-native-create-thumbnail` for Android SDK v.33 Tiramisu (Android 13). 

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a React Native project
2. Add `react-native-create-thumbnail` 
3. Ensure Gradle JDK 11 and Android SDK 33 are installed on the machine that's gonna be used for the build
4. Trigger app build with the following settings in `build.gradle`:
```
        compileSdkVersion = 33
        targetSdkVersion = 33
```

**Version**
`react-native-create-thumbnail` 1.5.1

**Expected Results**
Successful app build

**Actual Result**
The following compilation error appears:

```
<project-path>/node_modules/react-native-create-thumbnail/android/src/main/java/com/createthumbnail/CreateThumbnailModule.java:192: error: unreported exception IOException; must be caught or declared to be thrown
        retriever.release();
                         ^
```

**Comment by timoteialbu** [comment]
Would love to hear a resolution on this as well!

**Comment by souvik-ghosh** [comment]
fixed in v1.6.0

**Comment by nitishkumar325** [comment]
try {
            retriever.release();
        } catch (IOException e) {
            throw new IllegalStateException("File doesn't exist or not supported");
        }
i got the solution just warp this inside try-catch

**Comment by souvik-ghosh** [comment]
> try { retriever.release(); } catch (IOException e) { throw new IllegalStateException("File doesn't exist or not supported"); } i got the solution just warp this inside try-catch

This is added in `v2.0.0-rc.2`. Please use it if you're on android 13 (SDK v33)

**Comment by Parmar-Bansi** [comment]
same error yet!!

please provide proper solutions..
