### ISSUE TITLE
Issue generating thumbnails in iOS

### ISSUE THREAD

**Issue by adelrodriguez** [souvik-ghosh/react-native-create-thumbnail#7]
Package works perfectly on Android, but when creating thumbnails on iOS, both the `height` and `width` of the image are 0.

**Comment by souvik-ghosh** [comment]
@adelrodriguez Can you please provide bit more information, like - 

1. What type of video are you using(local/remote)?
2. The Request Object you are passing.

**Comment by adelrodriguez** [comment]
Hey @souvik-ghosh, sure:

1. I'm using a local video obtained from the user's Camera Roll using `@react-native-community/cameraroll`.
2. The request object:

```javascript
const transformedVideo = transformIOSPHVideoUriToALVideoUri(video);
const _videoInfo = await ProcessingManager.getVideoInfo(transformedVideo);

const _thumbnails = await Promise.all(Array(THUMBNAIL_AMOUNT).fill()
    .map(async (_, index) => {
      const second = Math.floor(_videoInfo.duration / (THUMBNAIL_AMOUNT - index));
      const res = await createThumbnail({
        url: video,
        type: 'local',
        timeStamp: second,
      });

      return res;
    }));
```

**Comment by souvik-ghosh** [comment]
The 0 `height` and `width` indicates that the underlying ios api could not parse the video file. It may happen in cases such as - unsupported file, invalid path etc. I'm not able to test this currently, as I don't have a physical iPhone; and we can't record videos in simulator. It's woking for remote videos, I've tested.

**Comment by souvik-ghosh** [comment]
@adelrodriguez Can you please check this with **v1.1.0** ? I've made a few changes to the iOS api.

**Comment by Atuldhaka** [comment]
hello @souvik-ghosh, i am getting this issue at random sometime it generates the thumbnail in ios and sometime it  says "File doesn't exist or not supported" please help me in this !

**Comment by souvik-ghosh** [comment]
@Atuldhaka Note that all video files might not be supported by the OS. This library depends on native OS APIs to generate the thumbnail. Can you first check if they are playable on the device?

**Comment by souvik-ghosh** [comment]
Closing as of now.
