### ISSUE TITLE
A problem occurred configuring project ':react-native-create-thumbnail'. > Installed Build Tools revision 31.0.0 is corrupted. Remove and install again using the SDK Manager.

### ISSUE THREAD

**Issue by Nsingh0007** [souvik-ghosh/react-native-create-thumbnail#74]
I am getting this error :- 

A problem occurred configuring project ':react-native-create-thumbnail'.
> Installed Build Tools revision 31.0.0 is corrupted. Remove and install again using the SDK Manager.

**Comment by souvik-ghosh** [comment]
The issue isn't related to this library and is caused by the android SDK installation in your system.
Please refer to this - https://stackoverflow.com/questions/68387270/android-studio-error-installed-build-tools-revision-31-0-0-is-corrupted
