### ISSUE TITLE
Execution failed for task ':react-native-create-thumbnail:compileDebugJavaWithJavac'

### ISSUE THREAD

**Issue by deflexable** [souvik-ghosh/react-native-create-thumbnail#75]
`/Users/macHome/Documents/codes/heavenya/mobile/node_modules/react-native-create-thumbnail/android/src/main/java/com/createthumbnail/CreateThumbnailModule.java:192: error: unreported exception IOException; must be caught or declared to be thrown
        retriever.release();`

This error happens when i change compileSdkVersion and targetSdkVersion from 31 to 33

**Comment by deflexable** [comment]
changing it to this works
```js
        try {
            retriever.release();
        } catch (IOException e) {
            e.printStackTrace();
        }
```

**Comment by souvik-ghosh** [comment]
@deflexable, Have you searched the previous issues? This was already answered. You need to use v2.0.0-rc.2 if you're on SDK v33.
