### ISSUE TITLE
'constructor MediaRecorder()' is deprecated. Deprecated in Java

### ISSUE THREAD

**Issue by Etaliya** [souvik-ghosh/react-native-create-thumbnail#89]
![Screenshot 2023-03-29 at 3 22 36 PM](https://user-images.githubusercontent.com/54949248/228497147-6f3e4b00-398b-4b1d-971b-cabcba7f8740.png)

**Comment by tdammy92** [comment]
@Etaliya  did you find a soltion to this ??, getting same error.

**Comment by souvik-ghosh** [comment]
fixed in the latest version
