### ISSUE TITLE
Android images saved to gallery

### ISSUE THREAD

**Issue by mobbdev** [souvik-ghosh/react-native-create-thumbnail#9]
All generated images are saved to android gallery. Is there a prop that can be set to remove thumbnails after generation?

**Comment by souvik-ghosh** [comment]
There is no prop like that but, I can work on stopping the generated image being shown in the gallery. 
Also, For storing the thumbnails, this library maintains a cache directory that has 100mb maximum size. We can make this size configurable If that helps.

**Comment by mobbdev** [comment]
Hey, thanks for replying. Sorry for the late response. I get reports from users that their gallery is spammed with images generated from videos (I am using this plugin to generate thumbnails from videos). Do I need to remove the images after using them, or the cache takes care of this itselft?

**Comment by souvik-ghosh** [comment]
@mobbdev yes, once the directory size becomes more than 100mb, it removes older generated images to free up 50mb. So the directory size cannot become more than 100mb in size.

**Comment by souvik-ghosh** [comment]
@mobbdev This issue should be fixed in **v1.1.0**. Added `.nomedia` in the the thumbnail directory to hide it from gallery.

**Comment by mobbdev** [comment]
@souvik-ghosh cool! Thank you!

**Comment by souvik-ghosh** [comment]
@mobbdev You're welcome!
One catch here is - the previous version of the app needs to be uninstalled from device or this may not work.
